const features = [ // Características de productos ORDENADAS


  { id: 1, name: 'Micrófono' },
  { id: 2, name: 'Potencia' },
  { id: 3, name: 'Woofers' },
  { id: 4, name: 'Tweeters' },
  { id: 5, name: 'Reguladores', hideInSearchPage: true },
  { id: 6, name: 'Display' },
  { id: 7, name: 'Efectos de Luces' },
  { id: 8, name: 'Entradas' },
  { id: 9, name: 'Conectividad' },
  { id: 10, name: 'Batería' },
  { id: 11, name: 'Duración de Batería' },
  { id: 12, name: 'Luces' },
  { id: 13, name: 'Funciones' },
  { id: 14, name: 'Caja (cuerpo)' },
  { id: 15, name: 'Otras Características', hideInSearchPage: true },
  { id: 16, name: 'Medidas del Producto', hideInSearchPage: true },
  { id: 17, name: 'Medidas de la Caja', hideInSearchPage: true },
  { id: 18, name: 'Peso', hideInSearchPage: true },
  { id: 19, name: 'EAN', hideInSearchPage: true },
  { id: 20, name: 'Radio FM' },
  { id: 21, name: 'Uso', hideInSearchPage: true },
  { id: 23, name: 'Efectos' },
  { id: 24, name: 'Cuerpo' },
  { id: 25, name: 'Efectos de Voz' },
  { id: 26, name: 'Carry-On' },
  { id: 27, name: 'Controles' },
  { id: 28, name: 'Tipo de conexión' },
  { id: 29, name: 'Longitud del cable' },
  { id: 30, name: 'Frecuencia de respuesta' },
  { id: 31, name: 'Impedancia' },
  { id: 32, name: 'Sensibilidad' },
  { id: 33, name: 'Sensibilidad (micrófono)' },
  { id: 34, name: 'Diámetro del diafragma' },
  { id: 35, name: 'Alcance de Bluetooth' },
  { id: 36, name: 'Versión de Bluetooth' },
  { id: 37, name: 'Formatos de Bluetooth' },
  { id: 38, name: 'Tiempo de carga' },
  { id: 39, name: 'Indicador de carga' },
  { id: 40, name: 'Tipo de batería' },
  { id: 41, name: 'Tamaño de pantalla' },
  { id: 42, name: 'Resolución' },
  { id: 43, name: 'Procesador' },
  { id: 44, name: 'Memoria RAM' },
  { id: 45, name: 'Almacenamiento' },
  { id: 46, name: 'Cámara' },
  { id: 47, name: 'Sistema Operativo' },
  { id: 48, name: 'Wifi' },
  { id: 49, name: 'Parlantes' },
  { id: 50, name: 'Micrófono' },
  { id: 51, name: 'Batería' },
  { id: 52, name: 'Tiempo de uso' },
  { id: 53, name: 'True Wireless Stereo' },
  { id: 54, name: 'Efectos de luces' },
  { id: 55, name: 'Empuñadura de Transp.' },
  { id: 56, name: 'Mobile Holder' },
  { id: 57, name: 'Altavoz' },
  { id: 58, name: 'Impermeabilidad' },
  { id: 59, name: 'Tensión' },
  { id: 60, name: 'Capacidad' },
  { id: 61, name: 'Temporizador digital' },
  { id: 62, name: 'Duración de temporizador' },
  { id: 63, name: 'Cantidad de velocidades' },
  { id: 64, name: 'Es planetaria' },
  { id: 65, name: 'Funciones' },
  { id: 66, name: 'Cantidad de accesorios' },
  { id: 67, name: 'Material de los accesorios' },
  { id: 68, name: 'Panel digital touch' },
  { id: 69, name: 'Uso recomendado' },
  { id: 70, name: 'Frecuencia' },
  { id: 71, name: 'Peso' },


  /*
  { id: 20, name: 'Power Bank' },
  { id: 21, name: 'Altura de trípode' },
  { id: 22, name: 'Características Técnicas' }
  */
]

export default features